


/**
 * Write a description of class scanner here.
 *
 * @author (1337mickey)
 * @version (a version number or a date)
 */

import java.util.Scanner;
public class scanner
{
  public static void main(String[] args){
      Scanner scan = new Scanner(System.in);
      
      System.out.println("Enter the age");
      int age = scan.nextInt();
      
      System.out.print("age" + age);
      
      
    }
}
